name: Terraform CI

on:
  pull_request:
    paths:
      - 'envs/**'
      - 'modules/**'
      - '.github/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment: dev   # <-- ADD THIS LINE

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # <-- ADDED THIS LINE
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # <-- ADDED THIS LINE
          aws-region: ${{ secrets.AWS_REGION }} # <-- ADDED THIS LINE

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: envs/dev
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/dev
        run: terraform plan -no-color
